language: node_js
node_js:
  - "8"

env:
  global:
    - secure: ZtnwnOPi4a/aECOOpBERlN4OFGpWfgfXuOvHXujSIHNrMxkYVFrXwfkd+n0/Qb5Hdn+nBX+BF3PbSPgL16jAjyd+8c1NE1Bd4luyT6M1nASY2f3KbIVd/5vdEZHX+xSkZCXhkKODJylTi8DzZgudab3D+AisB3OeRhXkj7iZAnZMk7nXY0EzDqPyjnn0nJMsMxhGf7CMGoNvEdS9Gm/AwT6QEsfb5arpFJerbUQUpJxa2ZTgOzsJWR/CwS2yZBRUrJC+oqFUOXM8IFb2e1Brvyp5cy9a72EM7+hIFxSJnvtzC5vxzNVAc5v8yCKfM/6TQW9UTXMqlzrny8E5LHq0xcef/ykXNzJM3mhU4oYvSjDQDL8hYksb8mBhW2skUnX24dTKQ3sx0RL5ABKYMBJqpRYIUDaPkl2zNFHncrDCwbEAMyiBVTYl5otgmsw2ssObGG7yWYqcQ2kgGblT5y6SL5xXNjPac7VkC/pwMQEggJwqM4lg/W0q9kjbaetiRMVv80lUuSDmW6AEArswuQw69REk+9H8aJc3I0mu/u1888Z1UXSBHQFyqP70QjPO1QIAoc8tjybpuYA4gX7jpD4rIdMHx9txJUKeCYRyjDjlGsEGxYq3I7R97i4vCkFqC21nqrVHiU2pMmhqyBBa9nqDtsvRLiRb/Y4rnSlr1Ddec2Y=
    - secure: Mo+OAy1+tp8nmydj0MZ9xJrbGVgFspWcogDbjMoCFqK1emtCmwx5yV6jlGLQGtMqMG8UMRrEAFYS+P86w8IzzGvKH54BrKbWdFE6T5Nxy349NTZpBmdYhdLT+N/8vb9FKjil5fxZGlHZvqimevRwEZis8lYrI7HXRt48T7xNsl70/zM8NVdj+nYpbMUiKT2SLKqtKT7gpcELsP5IfeiknF0xw/IJhcn4pBXqi+6hzedKK7zJA8uhBaxkekABK/mnUxbg7RRYM+T/ro8rDLyjz7s/gmUPAfKDVeUvuaHaSgGoeQPmmbW/6k102qNcqTuHF/cdjLLh6n4Q8VUFKKKzjeoLT6ij20H9mLw1dS7Ta4bqIunoKM3eNxJeUTfXoyqjxp5tVhGq+Atf5jLjskP8Zi4AqIsDxEs2GSgL52lcNZT5AZHwyzip1g1jCiNaIHWX3qK1InsKcsVkwcV5ecclh+M6G/SdrBXh8s7643VWG4K3ai6SDONg9DfFWjwv/16x12ohXJTFk0GbG8hKal190NHsodbDlZJmnHCOrsDulqfACG6rPGpvnb8Q28RiISQpP9/eqIKe51Ezpt9m4Ypk2lEJ5jF7e29xIEiAFfxs3IIyca+M22sV7xSTfzWJteF/DMP/SvTxC7ArV1zDDO3Cj4hzGJ0DAiTQXMPn3NNxkvA=

sudo: required
services:
  - docker
deploy:
  - provider: script
    script: bash travis.sh
    on:
      tags: true
      